### ISSUE TITLE
Schema validator function breaks and throw's wrong exception 

### ISSUE THREAD

**Issue by brunsgaard** [kolypto/py-good#4]
The code below explain the bug i found..

```
>>> from good import Schema
>>> s = Schema(dict)
>>> s(2)
...
good.schema.errors.Invalid: Wrong type: expected Dictionary, got Integer number
>>> s({})
{}
>>> s(2)
...
TypeError: 'dict' object is not callable
```

it should through `good.schema.errors.Invalid`, right?

**Comment by vartagg** [comment]
Probably this is already fixed. Can you check?

**Comment by maxrothman** [comment]
This is not fixed when using Python 2.7.13 and good 0.0.7.post0.

**Comment by kolypto** [comment]
Duplicate #3
